<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
    <NoWarn>1701;1702;CA1021;CA1707;CA1416</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Telerik.Documents.Core" Version="*" />
    <PackageReference Include="Telerik.Documents.Spreadsheet" Version="*" />
    <PackageReference Include="Telerik.Documents.Spreadsheet.FormatProviders.OpenXml" Version="*" />
  </ItemGroup>

</Project>
