<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Agents.AI.OpenAI" Version="1.0.0-preview.260212.1" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.AI" Version="10.3.0" />
    <PackageReference Include="Microsoft.Extensions.AI.OpenAI" Version="10.3.0" />
    <PackageReference Include="Azure.AI.OpenAI" Version="2.3.0-beta.1" />
    <PackageReference Include="Telerik.Documents.AI.AgentTools.Spreadsheet" Version="2026.1.206" />
    <PackageReference Include="Telerik.Documents.AI.AgentTools.Fixed" Version="2026.1.206" />
  </ItemGroup>

</Project>
